server:
  port: 8080

spring:
  application:
    name: edda

  rabbitmq:
    host: http://rabbit-server-service.mq.svc.cluster.local
    port: 8080
    username: guest
    password: guest
    #确认消息已发送到队列(Queue)
    publisher-returns: true

  #  redis:
  #    host: localhost
  #    port: 6379
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}] ${PID:- } --- [%15.15t] %-40.40logger{39} [%20.20M]: %m%n"
  level:
    root: INFO

bank:
  name: bank
  url: http://bank.ostone-platform.svc.cluster.local:8080
