server:
  port: 8081

spring:
  application:
    name: my-test
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}] ${PID:- } --- [%15.15t] %-40.40logger{39} [%20.20M]: %m%n"
  level:
    root: INFO

